name: MoonTalismans
main: me.sumbiz.moontalismans.MoonTalismansPlugin
version: 1.1.0
api-version: "1.20"
softdepend: [Nexo]

commands:
  talismans:
    usage: /talismans
    description: MoonTalismans commands
    permission: moontalismans.admin

permissions:
  moontalismans.admin:
    default: op
